package net.weg.wegproject.enums;

public enum LanguageAcronyms {
    AFG, ALB, ALG, AND, ANG, ANT, ASA, ARG, ARM, ARU, AUS, AUT, AZE, BAH, BAN,
    BAR, BDI, BEL, BEN, BER, BIH, BLR, BOT, BRN, CAF, CAN, CGO, CHI, CIV,  COD, COL,
    CPV, CRO, CYP, DJI, DOM, EGY, ESA, EST, ETH, FIN, FSM, GAM, NIR, WAL, GEO,
    GER, GRE, GUA, GUM, HAI, INA, IRI, IRL, IRQ,  ISR, JAM, JPN, KEN, KIR, KSA,
    LAO, LAT, LBA, LCA, LBN, LTU, LUX, MAR, MAW, MDV, MGL, MKD, MLT, MON, MRI,
    MYA, NCA, NEP, NIG, NRU, OMA, PAN, PER, PLE, PNG, POR, PUR, ROU, SAF, RWA,
    SLE, SMR, SOM, SRI, STP, SUR, SWE, SYR, TGA, TJKte, TLS, TPE, TRT, TUN, TUV,
    URU, VEN, ZAM, ZIM, MIX, AHO, ANZ, BOH, BWI, FRG, HBR, IHO, KHM, LIB, MAL,
    RHN, RHS, ROM, SAA, SAU, SIN, TCH, VOL, YAR, YUG, SGP, SEN, UGA, NGY}